-- Fix Schema Migration pour Hibernat 6 Compatibility
-- Corrige les types de colonnes PRIMARY KEY de serial/integer vers bigint
-- Pour éviter: "Schema-validation: wrong column type encountered"

-- Étape 1: Supprimer les vues qui dépendent de contrats_employes
DROP VIEW IF EXISTS vue_employes_detail CASCADE;

-- Étape 2: Modifier les types de colonne primaires de SERIAL à BIGINT
-- NOTE: Cela nécessite de créer une nouvelle colonne, de copier les données, 
-- de supprimer l'ancienne, et de renommer

-- Fonction utilitaire pour convertir une colonne de serial en bigint
-- 2a. niveaux
ALTER TABLE IF EXISTS niveaux
DROP CONSTRAINT IF EXISTS niveaux_pkey;

ALTER TABLE IF EXISTS niveaux
ADD COLUMN id_new BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;

UPDATE niveaux SET id_new = id;
ALTER TABLE niveaux DROP COLUMN id;
ALTER TABLE niveaux RENAME COLUMN id_new TO id;

-- 2b. users  
ALTER TABLE IF EXISTS users
DROP CONSTRAINT IF EXISTS users_pkey;

ALTER TABLE IF EXISTS users
ADD COLUMN id_new BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;

UPDATE users SET id_new = id;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users RENAME COLUMN id_new TO id;

-- 2c. contrats_employes
-- D'abord on supprime les FKs vers cette table
ALTER TABLE IF EXISTS profils_professeurs DROP CONSTRAINT IF EXISTS fk_prof_contrat;
ALTER TABLE IF EXISTS profils_directeurs DROP CONSTRAINT IF EXISTS fk_dir_contrat;
ALTER TABLE IF EXISTS profils_secretariat DROP CONSTRAINT IF EXISTS fk_sec_contrat;
ALTER TABLE IF EXISTS profils_comptables DROP CONSTRAINT IF EXISTS fk_compt_contrat;

ALTER TABLE IF EXISTS contrats_employes
DROP CONSTRAINT IF EXISTS contrats_employes_pkey,
DROP CONSTRAINT IF EXISTS fk_ce_user,
DROP CONSTRAINT IF EXISTS fk_ce_type;

ALTER TABLE IF EXISTS contrats_employes
ADD COLUMN id_new BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;

UPDATE contrats_employes SET id_new = id;

-- Aussi corriger user_id et type_contrat_id dans la même table
ALTER TABLE contrats_employes
ADD COLUMN user_id_new BIGINT,
ADD COLUMN type_contrat_id_new BIGINT;

UPDATE contrats_employes SET 
  user_id_new = user_id,
  type_contrat_id_new = type_contrat_id;

ALTER TABLE contrats_employes DROP COLUMN id, DROP COLUMN user_id, DROP COLUMN type_contrat_id;
ALTER TABLE contrats_employes RENAME COLUMN id_new TO id;
ALTER TABLE contrats_employes RENAME COLUMN user_id_new TO user_id;
ALTER TABLE contrats_employes RENAME COLUMN type_contrat_id_new TO type_contrat_id;

-- Ajouter les FKs
ALTER TABLE contrats_employes
ADD CONSTRAINT fk_ce_user FOREIGN KEY (user_id) REFERENCES users(id),
ADD CONSTRAINT fk_ce_type FOREIGN KEY (type_contrat_id) REFERENCES types_contrats_employes(id);

-- Étape 3: Restaurer la vue
CREATE OR REPLACE VIEW vue_employes_detail AS
SELECT u.id AS user_id,
       u.email,
       u.is_active,
       r.nom AS role_nom,
       COALESCE(pp.nom, pd.nom, ps.nom, pc.nom) AS nom,
       COALESCE(pp.prenom, pd.prenom, ps.prenom, pc.prenom) AS prenom,
       ce.id AS contrat_id,
       ce.reference_contrat,
       ce.fonction,
       COALESCE(ce.sexe, pp.sexe, ps.sexe, pd.sexe, pc.sexe, 'H'::bpchar) AS sexe,
       COALESCE(pp.photo_url, pd.photo_url, ps.photo_url, pc.photo_url) AS photo_url,
       tce.code AS type_contrat_code,
       tce.libelle AS type_contrat_libelle,
       ce.date_debut,
       ce.date_fin,
       ce.document_url,
       ce.salaire_mensuel,
       ce.heures_hebdo,
       pp.id_matiere,
       m.nom AS matiere_nom,
       CASE
           WHEN (ce.date_fin IS NULL) THEN NULL::integer
           ELSE GREATEST((ce.date_fin - CURRENT_DATE), 0)
       END AS jours_restants
FROM (((((((((users u
  JOIN user_roles ur ON ((ur.user_id = u.id)))
  JOIN roles r ON ((r.id = ur.role_id)))
  LEFT JOIN profils_professeurs pp ON ((pp.user_id = u.id)))
  LEFT JOIN profils_directeurs pd ON ((pd.user_id = u.id)))
  LEFT JOIN profils_secretariat ps ON ((ps.user_id = u.id)))
  LEFT JOIN profils_comptables pc ON ((pc.user_id = u.id)))
  LEFT JOIN contrats_employes ce ON ((ce.id = COALESCE(pp.id_contrat, pd.id_contrat, ps.id_contrat, pc.id_contrat))))
  LEFT JOIN types_contrats_employes tce ON ((tce.id = ce.type_contrat_id)))
  LEFT JOIN matieres m ON ((m.id = pp.id_matiere)))
 WHERE ((r.nom)::text <> ALL ((ARRAY['etudiant'::character varying, 'parent'::character varying])::text[]));
